### ISSUE TITLE
Can you tell me what your theme name is?

### ISSUE THREAD

**Issue by iuunhao** [mikker/lightline-theme-pencil#1]
Can you tell me what your theme name is?

**Comment by mikker** [comment]
It's made to go along with Pencil https://github.com/reedes/vim-colors-pencil.

**Comment by mikker** [comment]
You might also want to try my slightly modified fork, Dimcil: https://github.com/mikker/vim-dimcil 👍

**Comment by iuunhao** [comment]
so perfect
